### ISSUE TITLE
Questions about configuration

### ISSUE THREAD

**Issue by jsponz** [t0mer/voicy#5]
Hi, 

Thanks for this nice code!

I have a couple of questions about the configuration. 

1/ In the 'config.ini' file, 

- what should I put in the field: 'bot.allowedid='?
- do you have examples for these fields? 

[RESULTS]
result.ok=
result.error=

2/ I launch the bot via docker-compose, but it is continuously restarting (if I run docker-compose ps). Is this because of a wrong configuration of the 'config.ini' file

Thanks!

**Comment by t0mer** [comment]
> 

Hi @jsponz ,
1. the bot.allowedid is not yet implemented, basically it will allow only certain telegram Id's to communicate with the bot.

as for the [RESULTS] section:
 result.ok= This is the message we return to the bot on success
result.error=This is the message we return to the bot on error

As for the error, can you share the log?

Thanks (:

**Comment by jsponz** [comment]
Thanks for your answer. 

Here the logs:

```
Attaching to voicy
voicy    | Traceback (most recent call last):
voicy    |   File "/app/voicy.py", line 22, in <module>
voicy    |     config_file = open("config/config.ini", encoding="utf-8")
voicy    | FileNotFoundError: [Errno 2] No such file or directory: 'config/config.ini'
voicy    | Traceback (most recent call last):
voicy    |   File "/app/voicy.py", line 22, in <module>
voicy    |     config_file = open("config/config.ini", encoding="utf-8")
voicy    | FileNotFoundError: [Errno 2] No such file or directory: 'config/config.ini'
```
